version: "3.8"
networks:
  msnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
services:
  db:
    container_name: db-travel
    restart: unless-stopped
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=defaultdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      msnetwork:
        ipv4_address: 172.21.0.2
  app:
    container_name: travel
    build: 
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - 3000:3000
      - 443:443
    volumes:
      - ./:/home/travel
    environment:
      - PGUSER=root
      - PGPASSWORD=12345
      - PGDATABASE=defaultdb
      - PGHOST=db
    depends_on: 
      - db
    networks:
      msnetwork:
        ipv4_address: 172.21.0.3
  nginx-proxy:
    container_name: travel-proxy
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - app
      - db
    ports:
      - "80:80"
    networks:
      msnetwork:
        ipv4_address: 172.21.0.4
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin,
    networks:
      msnetwork:
        ipv4_address: 172.21.0.5
volumes:
  pgdata: {}
  pgadmin-data: {}