import { Router } from 'express';
import { Gallery, Category, Auth, Feature, Hotel, Order, Package, Partner, Profile, Review, Service, Team, User, Callback, PaymentChanel,  Destination, Payment, Tag, GroupController, PeriodeController, JournalTypeController, TaxController, AccountController, BeginningBalanceController, JournalController, LedgerController, ReportController } from '../controllers';

const routers = Router();
routers.use('/category', Category);
routers.use('/feature', Feature);
routers.use('/gallery', Gallery);
routers.use('/hotel', Hotel);
routers.use('/order', Order);
routers.use('/package', Package);
routers.use('/partner', Partner);
routers.use('/profile', Profile);
routers.use('/review', Review);
routers.use('/service', Service);
routers.use('/team', Team);
routers.use('/user', User);
routers.use('/callback', Callback);
routers.use('/payment-chanel', PaymentChanel);
routers.use('/auth', Auth);
routers.use('/destination', Destination);
routers.use('/payment', Payment);
routers.use('/accounting/tag', Tag);
routers.use('/accounting/group', GroupController);
routers.use('/accounting/periode', PeriodeController);
routers.use('/accounting/journal-type', JournalTypeController);
routers.use('/accounting/journal', JournalController);
routers.use('/accounting/tax', TaxController);
routers.use('/accounting/account', AccountController);
routers.use('/accounting/balance', BeginningBalanceController);
routers.use('/accounting/ledger', LedgerController);
routers.use('/accounting/report', ReportController);

export default routers;